---
   - name: check if DB exists
     shell: mysql -e 'SHOW DATABASES;' | grep {{ wordpress_db }}
     register: dbstatus
     ignore_errors: True

   - name: Create a new database with name '{{ wordpress_db }}'
     mysql_db: name={{ wordpress_db }} encoding=utf8 collation=utf8_general_ci state=present
     when: dbstatus.rc != 0

   - name: Create the database user for wordpress
     mysql_user: name={{ wordpress_user }} password={{ wordpress_passwd }} priv={{ wordpress_db }}.*:ALL state=present
